blank_issues_enabled: true
contact_links:
  - name: Support
    url: https://github.com/suryanshvermaa/Conference_website/blob/main/SUPPORT.md
    about: Please check SUPPORT.md for troubleshooting and support options.
